/**
 * Template Functor vs std::function
 * 
 * This code demonstrates the performance difference between:
 * - Template functors (compile-time binding, can be inlined)
 * - std::function (runtime polymorphism, type-erased)
 * 
 * Key concepts:
 * - Template functors are resolved at compile time
 * - Compiler can inline the functor's operator()
 * - std::function uses type erasure (similar to virtual)
 * - std::function adds indirection and prevents inlining
 * 
 * std::function overhead:
 * - Heap allocation for large callables
 * - Indirect function call (like virtual)
 * - Cannot be inlined
 * 
 * Compile: g++ -O3 -std=c++17 -o 02_template_functor 02_template_functor.cpp
 * Run: ./02_template_functor
 */

#include <iostream>
#include <vector>
#include <functional>
#include <chrono>
#include <iomanip>
#include <random>
#include <numeric>
#include <algorithm>

// Timer class for measuring execution time
class Timer {
    using Clock = std::chrono::high_resolution_clock;
    std::chrono::time_point<Clock> start;
public:
    Timer() : start(Clock::now()) {}
    void reset() { start = Clock::now(); }
    double elapsed_ms() const {
        return std::chrono::duration<double, std::milli>(Clock::now() - start).count();
    }
};

// Prevent compiler from optimizing away results
volatile double sink;

// ============================================
// FUNCTOR DEFINITIONS
// ============================================

/**
 * A simple functor class
 * 
 * Functors are classes with operator() defined.
 * When used with templates, the compiler knows the exact type
 * and can inline the call completely.
 */
struct MultiplyFunctor {
    double factor;
    
    explicit MultiplyFunctor(double f) : factor(f) {}
    
    // This operator() can be inlined when type is known
    double operator()(double x) const {
        return x * factor;
    }
};

/**
 * Another functor for comparison
 */
struct AddFunctor {
    double offset;
    
    explicit AddFunctor(double o) : offset(o) {}
    
    double operator()(double x) const {
        return x + offset;
    }
};

/**
 * A more complex functor
 */
struct PolynomialFunctor {
    double a, b, c;  // ax² + bx + c
    
    PolynomialFunctor(double a_, double b_, double c_) : a(a_), b(b_), c(c_) {}
    
    double operator()(double x) const {
        return a * x * x + b * x + c;
    }
};

// ============================================
// TRANSFORM IMPLEMENTATIONS
// ============================================

/**
 * Template version - functor type known at compile time
 * 
 * The compiler generates a specialized version for each functor type.
 * The functor's operator() can be fully inlined.
 */
template <typename Func>
void transform_template(std::vector<double>& data, Func func) {
    for (size_t i = 0; i < data.size(); ++i) {
        // Direct call to func.operator()
        // Compiler knows exact type, can inline
        data[i] = func(data[i]);
    }
}

/**
 * std::function version - type-erased
 * 
 * std::function can hold any callable with matching signature.
 * This flexibility comes at a cost:
 * - Type information is erased at compile time
 * - Indirect call through internal vtable-like mechanism
 * - Cannot be inlined
 */
void transform_std_function(std::vector<double>& data, 
                           const std::function<double(double)>& func) {
    for (size_t i = 0; i < data.size(); ++i) {
        // Indirect call - cannot be inlined
        // Similar overhead to virtual function
        data[i] = func(data[i]);
    }
}

/**
 * Raw function pointer version
 * 
 * Function pointers also prevent inlining (unless the compiler
 * can prove which function is being called through constant propagation).
 */
void transform_function_pointer(std::vector<double>& data, 
                                double (*func)(double)) {
    for (size_t i = 0; i < data.size(); ++i) {
        // Indirect call through function pointer
        data[i] = func(data[i]);
    }
}

// A regular function for testing function pointers
double multiply_by_two(double x) {
    return x * 2.0;
}

/**
 * Lambda version (inline style)
 * 
 * Lambdas are actually functor classes generated by the compiler.
 * When used directly (not through std::function), they can be inlined.
 */
void transform_lambda_inline(std::vector<double>& data, double factor) {
    // This lambda is a unique type, known at compile time
    auto lambda = [factor](double x) { return x * factor; };
    
    for (size_t i = 0; i < data.size(); ++i) {
        // Direct call - compiler knows lambda type
        data[i] = lambda(data[i]);
    }
}

/**
 * Using std::transform with different callable types
 * Demonstrates the standard algorithm approach
 */
template <typename Func>
void transform_std_algorithm(std::vector<double>& data, Func func) {
    std::transform(data.begin(), data.end(), data.begin(), func);
}

int main() {
    std::cout << "=== Template Functor vs std::function ===\n\n";
    
    // Configuration
    const size_t N = 50000000;  // 50 million elements
    const int num_runs = 5;
    
    std::cout << "Array size: " << N << " elements\n\n";
    
    // Create test data
    std::vector<double> original(N);
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_real_distribution<double> dist(0.0, 100.0);
    
    for (size_t i = 0; i < N; ++i) {
        original[i] = dist(gen);
    }
    
    std::vector<double> data;  // Working copy
    
    // Create functors
    MultiplyFunctor multiply_functor(2.0);
    std::function<double(double)> multiply_std_function = 
        [](double x) { return x * 2.0; };
    
    // ==========================================
    // Test 1: Template with functor
    // ==========================================
    std::cout << "=== Test 1: Template Functor ===\n";
    std::cout << "(Compile-time binding, can be inlined)\n";
    {
        double total_time = 0;
        for (int run = 0; run < num_runs; ++run) {
            data = original;
            Timer timer;
            transform_template(data, multiply_functor);
            total_time += timer.elapsed_ms();
        }
        sink = data[N/2];
        
        std::cout << "Average time: " << std::fixed << std::setprecision(2) 
                  << total_time / num_runs << " ms\n\n";
    }
    
    // ==========================================
    // Test 2: std::function
    // ==========================================
    std::cout << "=== Test 2: std::function ===\n";
    std::cout << "(Type-erased, indirect call)\n";
    {
        double total_time = 0;
        for (int run = 0; run < num_runs; ++run) {
            data = original;
            Timer timer;
            transform_std_function(data, multiply_std_function);
            total_time += timer.elapsed_ms();
        }
        sink = data[N/2];
        
        std::cout << "Average time: " << std::fixed << std::setprecision(2) 
                  << total_time / num_runs << " ms\n\n";
    }
    
    // ==========================================
    // Test 3: Function pointer
    // ==========================================
    std::cout << "=== Test 3: Function Pointer ===\n";
    std::cout << "(Indirect call through pointer)\n";
    {
        double total_time = 0;
        for (int run = 0; run < num_runs; ++run) {
            data = original;
            Timer timer;
            transform_function_pointer(data, multiply_by_two);
            total_time += timer.elapsed_ms();
        }
        sink = data[N/2];
        
        std::cout << "Average time: " << std::fixed << std::setprecision(2) 
                  << total_time / num_runs << " ms\n\n";
    }
    
    // ==========================================
    // Test 4: Inline lambda
    // ==========================================
    std::cout << "=== Test 4: Inline Lambda ===\n";
    std::cout << "(Type known, can be inlined)\n";
    {
        double total_time = 0;
        for (int run = 0; run < num_runs; ++run) {
            data = original;
            Timer timer;
            transform_lambda_inline(data, 2.0);
            total_time += timer.elapsed_ms();
        }
        sink = data[N/2];
        
        std::cout << "Average time: " << std::fixed << std::setprecision(2) 
                  << total_time / num_runs << " ms\n\n";
    }
    
    // ==========================================
    // Test 5: std::transform with functor
    // ==========================================
    std::cout << "=== Test 5: std::transform + Functor ===\n";
    std::cout << "(Standard algorithm with template)\n";
    {
        double total_time = 0;
        for (int run = 0; run < num_runs; ++run) {
            data = original;
            Timer timer;
            transform_std_algorithm(data, multiply_functor);
            total_time += timer.elapsed_ms();
        }
        sink = data[N/2];
        
        std::cout << "Average time: " << std::fixed << std::setprecision(2) 
                  << total_time / num_runs << " ms\n\n";
    }
    
    // ==========================================
    // Test 6: std::transform with lambda
    // ==========================================
    std::cout << "=== Test 6: std::transform + Lambda ===\n";
    std::cout << "(Standard algorithm with lambda)\n";
    {
        double total_time = 0;
        for (int run = 0; run < num_runs; ++run) {
            data = original;
            Timer timer;
            std::transform(data.begin(), data.end(), data.begin(),
                [](double x) { return x * 2.0; });
            total_time += timer.elapsed_ms();
        }
        sink = data[N/2];
        
        std::cout << "Average time: " << std::fixed << std::setprecision(2) 
                  << total_time / num_runs << " ms\n\n";
    }
    
    // Summary
    std::cout << "=== Summary ===\n\n";
    
    std::cout << "Callable Performance Hierarchy (fastest to slowest):\n\n";
    
    std::cout << "1. TEMPLATE FUNCTOR / LAMBDA:\n";
    std::cout << "   - Type known at compile time\n";
    std::cout << "   - operator() can be fully inlined\n";
    std::cout << "   - No call overhead in hot loops\n\n";
    
    std::cout << "2. FUNCTION POINTER:\n";
    std::cout << "   - Indirect call (prevents inlining)\n";
    std::cout << "   - Can be predicted if same pointer used\n";
    std::cout << "   - Lighter than std::function\n\n";
    
    std::cout << "3. std::function:\n";
    std::cout << "   - Type erasure overhead\n";
    std::cout << "   - Possible heap allocation\n";
    std::cout << "   - Indirect call (like virtual)\n";
    std::cout << "   - Most flexible but slowest\n\n";
    
    std::cout << "When to use each:\n\n";
    
    std::cout << "Template/Lambda:\n";
    std::cout << "  - Hot loops, performance-critical paths\n";
    std::cout << "  - Callable known at compile time\n";
    std::cout << "  - Want inlining optimization\n\n";
    
    std::cout << "std::function:\n";
    std::cout << "  - Storing callbacks for later use\n";
    std::cout << "  - Callable type not known at compile time\n";
    std::cout << "  - Interface stability more important than speed\n";
    std::cout << "  - Non-performance-critical code paths\n";
    
    return 0;
}
